version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5432:5432"

  #app:
   #build:
     # context: .
      #dockerfile: Dockerfile
   # volumes:
     # - .:/app
   # ports:
    #  - "3000:3000"
   # depends_on:
    #  - postgres
